#!/bin/bash -eu

conts="$(docker ps -aq | grep spitting | uniq)"
if [ "$conts" ]; then
  set $conts
  docker stop "$@"
  docker rm "$@"
fi

images="$(docker images -q | grep jhaemer | uniq)"
[ "$images" ] || exit 0
set $images

docker rmi "$@"


