#!/bin/bash -eu

conts="$(docker ps -aq | uniq)"
[ "$conts" ] || exit 0
set $conts

docker stop "$@"
docker rm "$@"

images="$(docker images -q | uniq)"
[ "$images" ] || exit 0
set $images

docker rmi "$@"


